# Development Docker Compose Configuration

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: async-upload-backend
    ports:
      - "8080:8080"
    volumes:
      # Mount uploads directory for persistence
      - ./backend/uploads:/app/uploads
      # Mount source code for development (optional)
      # - ./backend:/app
    environment:
      - GO_ENV=development
    networks:
      - async-upload-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: async-upload-frontend
    ports:
      - "3000:80"
    networks:
      - async-upload-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  async-upload-network:
    driver: bridge

volumes:
  uploads:
    driver: local
